[project]
name = "new"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=2.3.8",
    "google>=3.0.0",
    "google-genai>=1.54.0",
    "sqlalchemy>=2.0.44",
    "streamlit>=1.32.0",
]
